// <auto-generated />
using Bingo.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bingo.Migrations
{
    [DbContext(typeof(BingoContext))]
    [Migration("20230212004905_historialCartones")]
    partial class historialCartones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Bingo.Models.HistorialBolillero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FechaYHora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDeBolilla")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistorialBolilleros");
                });

            modelBuilder.Entity("Bingo.Models.HistorialCartones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Carton1")
                        .HasColumnType("int");

                    b.Property<int>("Carton2")
                        .HasColumnType("int");

                    b.Property<int>("Carton3")
                        .HasColumnType("int");

                    b.Property<int>("Carton4")
                        .HasColumnType("int");

                    b.Property<string>("FechaYHora")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HistorialCartones");
                });
#pragma warning restore 612, 618
        }
    }
}
